name: Extended Testing

on:
  workflow_dispatch:
  schedule:
    # Run weekly on Sundays at 2 AM UTC
    - cron: '0 2 * * 0'

permissions:
  contents: read

jobs:
  nightly-test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Install Neovim (nightly)
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: nightly

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ripgrep fd-find

      - name: Setup Neovim configuration
        run: |
          mkdir -p ~/.config
          ln -s $GITHUB_WORKSPACE ~/.config/nvim

      - name: Install plugins
        timeout-minutes: 5
        run: |
          nvim --headless -c "Lazy! sync" -c "qa" 2>&1 || true

      - name: Test configuration loading
        run: |
          nvim --headless -c "echo 'Config loaded successfully'" -c "qa" 2>&1

      - name: Run health check
        continue-on-error: true
        run: |
          nvim --headless -c "checkhealth" -c "qa" 2>&1 | head -50

  local-test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Install Neovim (stable)
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: stable

      - name: Setup configuration
        run: |
          mkdir -p ~/.config
          ln -s $GITHUB_WORKSPACE ~/.config/nvim

      - name: Run local test suite
        continue-on-error: true
        run: |
          if [ -f test/run_tests.sh ]; then
            chmod +x test/run_tests.sh
            timeout 300 ./test/run_tests.sh || true
          fi
